server:
  port: 8001
  servlet:
    context-path: /


#add appropriate database url and credentials
#spring:
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: logs/app.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.ex: DEBUG
    org.hibernate: ERROR


angular:
  url: 'http://localhost:4200'